version: '3'
services:
  tomcat:
    build:
      context: .
      args:
        - SPRING_PROFILE=prod
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./ssl:/usr/local/tomcat/conf/ssl
      - ./server.xml:/usr/local/tomcat/conf/server.xml
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
