version: '3'
services:
  tomcat:
    build:
      context: .
      args:
        - SPRING_PROFILE=local
    ports:
      - "8080:8080"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
      -
  vault-dev:
    image: vault:latest
    container_name: vault-dev
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: "root"
      VAULT_DEV_LISTEN_ADDRESS: "0.0.0.0:8200"
    ports:
      - "8201:8201"
    volumes:
      - C:/java/vault/data:/vault/file
    networks:
      - vault-network
    command: "server -dev -dev-root-token-id=root -dev-listen-address=0.0.0.0:8200"

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge

volumes:
  portainer_data: