version: '3'
services:
  tomcat:
    build:
      context: .
      args:
        - SPRING_PROFILE=prod
    ports:
      - "8080:8080"
      - "443:443"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  vault:
    image: vault:1.13.1
    container_name: vault
    cap_add:
      - IPC_LOCK
    environment:
      VAULT_LOCAL_CONFIG: |
        {
          "backend": {
            "file": {
              "path": "/vault/file"
            }
          },
          "listener": [
            {
              "tcp": {
                "address": "0.0.0.0:8200",
                "tls_disable": 1
              }
            }
          ],
          "ui": true
        }
    ports:
      - "8200:8200"
    volumes:
      - /var/lib/vault/data:/vault/file
    networks:
      - vault-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - vault-network

networks:
  vault-network:
    driver: bridge

volumes:
  portainer_data: