version: '3'
services:
  tomcat:
    build:
      context: .
      args:
        - SPRING_PROFILE=local
    ports:
      - "8080:8080"
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"